---
apiVersion: v1
kind: Pod
metadata:
  name: vulong25-hello-a
  labels:
    greeting: personalized
spec:
  containers:
    - name: vulong25-hello-a
      image: ubuntu:18.04
      env:
        - name: NAME
      command: ['sh', '-c', 'echo "Hello, $(NAME)" && sleep 3600']

