---
apiVersion: v1
kind: Service
metadata:
  name: vulong25-test-redis
  labels:
    app: test-redis-service
    username: vulong25
    env: test
spec:
  type: ClusterIP
  selector:
    app: vulong25-test-redis
  ports:
  - name: vulong25-test-redis
    port: 6379
    targetPort: 6379