---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulong25-hello-deployment
  labels:
    greeting: personalized
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: vulong25-hello-deployment
          image: ubuntu:18.04
          env:
            - name: NAME
              value: Long
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ['sh', '-c', 'echo "Hello, $(NAME) from IP $(POD_IP)" && sleep 3600']

